### ISSUE TITLE
Data processing decisions we need to make/update/confirm when we have SB19plus info/update .psa:

### ISSUE THREAD

**Issue by coleary-noaa** [afsc-gap-products/gapctd#6]
1. data processing: output variables we want - currently set to conductivity (S/m), density (kg/m^3), depth (salt water, meters, lat 0), salinity practical (PSU), temperatures ITS-90 deg C, pressure 
2. filtering: filter type A or B
3. filtering: desired filter time constants
4. align CTD: advance values (e.g., If 0 seconds is entered, alignment relative to pressure (and time) remains unchanged for that variable.) - help file has suggested temperature and conductivity alignment suggestions for each model (e.g., 19plus is +0.5)
5. cell thermal mass: need alpha and beta entries (thermal anomaly amplitude & time constant):  typical values in table above and equation in Formulas in help file (e.g., SBE 19plus or 19plus V2 with TC duct and 2000 rpm pump: alpha = 0.04, 1/beta = 8.0 )
6. window filters: specify which variables to run window filter on and the filters used (boxcar, cosine, gaussian, median, triangles) , & window size[scans]: default is set to 5
7. Derive TEOS-10 options: Select TEOS-10 variables (i selected absolute salinity, conservative temperature, and density for the test)
8. Derive TEOS-10 options: instrument type (Other, SBE 21 Seacat Thermosalinograph, SBE 45 MicroTSG Thermosalinograph) & sources for Lat/Lon data when NMEA data not present, source for pressure data when pressure column is not present
9. Derive options: need to select derived variables - selected depth (salt water, m), density (kg/m^3), potential temp (ITS-90 deg C), salinity (PSU) for now

**Comment by sean-rohan-NOAA** [comment]
Made a couple of modifications to the batch processing SBE19(non-plus) files for the .psa after some additional reading.

- In DataCnv: Only output strain gauge pressure, conductivity, and temperature.
- Changed the time windows for the low-pass filter.

**Comment by sean-rohan-NOAA** [comment]
#2-3: The different filtering options are just for setting up two different filters. The default Filter.psa options are for the 911plus. Recommendation for 19plus V2 is pressure +1, temperature and conductivity +0.5 if there are no outliers. I set up the 19plus Filter.psa with the recommended settings. 

#4: I set up the AlignCTD.psa file with temperature +0.5 and no lag for conductivity. May need to revisit this decision (Sea-Bird's recommendation is +0.0-0.1).

**Comment by sean-rohan-NOAA** [comment]
Advance options for AlignCTD:

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-8209be0a-7fff-4b69-6277-426ccd188146"><div dir="ltr" style="margin-left:0pt;" align="left">

  | Temperature advance (s)
-- | --
Conductivity advance (s) | +0.0 | +0.25 | +0.50 | +0.625 | +0.75 | +1.00 | +1.25
+0.0 | x | x | x | x | x | x | x
+0.05 |   |   | x |   | x | x |  
+0.10 |   |   | x |   | x | x |  

</div></b>
</body>
</html>

**Comment by sean-rohan-NOAA** [comment]
Method in #31 seems promising for replacing step 5.

**Comment by sean-rohan-NOAA** [comment]
> Method in #31 seems promising for replacing step 5.

Process using 'typical' parameters:
1. Setup processing directory and move .hex, .psa, .xmlcon, and .bat files.
2. Convert hex files to cnv with the following channels as outputs: Temperature (T), Conductivity (C), Pressure
4. Window filter T, C, pressure (median, 5 scan window)
5. Low-pass filter (temperature = 0.5, salinity = 0.5, pressure = 1.0)
6. Align (temperature = +0.5)
7. Cell thermal mass correction (ɑ = 0.04, τ[CTM] = 8)
8. Loop edit (minimum speed = 0.05 m/s)
9. Derive EOS-80
10. Calculate bottom temperature, bottom salinity, bottom sound speed
11. Split upcasts and downcasts using custom method
12. Calculate 1-m bin averages.

Process using estimated align and celltm parameters:
1. Setup processing directory and move .hex, .psa, .xmlcon, and .bat files.
2. Convert hex files to cnv with outputs: temperature (T), conductivity (C), pressure
6. Window filter T, C, pressure (median, 5 scan window)
7. Low-pass filter (temperature = 0.5, salinity = 0.5, pressure = 1.0)
8. Loop edit (minimum speed = 0.05 m/s)
9. Derive EOS-80 and TEOS-10
10. Calculate bottom temperature, bottom salinity, bottom sound speed.
11. Split upcasts and downcasts using custom method.
12. Calculate 1-m bin averages.
13. Estimate temperature alignment using the adjustment that maximizes correlation between temperature and conductivity channels.
14. Align temperature for downcasts and upcasts using output of step 8.
15. Derive EOS-80 and TEOS-10
16. Split upcasts and downcasts using custom method.
17. Calculate 1-m bin averages.
18. Estimate cell thermal mass correction parameters that minimize the path distance of 1-m binned salinity profiles.
19. Cell thermal mass correction on downcasts and upcasts using output of step 14.
20. Derive EOS-80 and TEOS-10.
21. Split upcasts and downcasts using custom method.
22. Calculate 1-m bin averages.

Select and clean profiles generated using the 'typical' or estimated method:
1. Select the best profile for each cast based on path distance of salinity profiles. Profiles compared: binned profiles processed using 'typical' module values, binned output after step 11, binned output after step 16, binned output after step 21.
2. Flag density inversions and interpolate flagged values based on N2 inversion. 
3. Manually review profiles and flag any remaining bad data. Replace bad data with interpolated values.
4. Review profiles.
5. Calculate surface temperature, surface salinity, average sound speed.

**Comment by sean-rohan-NOAA** [comment]
```
# Run using 'typical' parameters
gapctd::run_method(vessel = vessel,
                   year = year,
                   region = region,
                   channel = channel,
                   processing_method = "sbe19plus_v2",
                   storage_directory = here::here("output", "sbe19plus_v2"),
                   ctd_dir = ctd_dir)

# Process without alignment or cell thermal mass correction
gapctd::run_method(vessel = vessel,
                   year = year,
                   region = region,
                   channel = channel,
                   processing_method = try_method,
                   storage_directory = here::here("output", try_method),
                   ctd_dir = ctd_dir)

# Estimate alignment parameters
alignment_df <-
  gapctd::run_alignment_calcs(
    profile_files = sort(c(
      list.files(
        here::here("output", try_method),
        full.names = TRUE,
        pattern = "downcast.cnv"
      ),
      list.files(
        here::here("output", try_method),
        full.names = TRUE,
        pattern = "upcast.cnv"
      )
    )),
    make_diagnostic_plots = TRUE,
    min_pressure = 4,
    cor_method = "spearman",
  )

saveRDS(object = alignment_df, here::here("output", paste0(region, "_", year, "_", vessel, "_align_pars.rds")))

# Align profile data

gapctd::run_method(vessel = vessel,
                   year = year,
                   region = region,
                   channel = channel,
                   processing_method = try_method,
                   storage_directory = here::here("output", paste0(try_method, "_align")),
                   ctd_dir = ctd_dir,
                   alignment_df = readRDS(file = here::here("output", paste0(region, "_", year, "_", vessel, "_align_pars.rds"))))

# Estimate cell thermal mass correction parameters for aligned data

ctm_adjust_df <- gapctd::run_ctm_adjust_tsarea(profile_files = sort(c(list.files(here::here("output", "sbe19plus_v0_align"),
                                                                                 full.names = TRUE, pattern = "downcast.cnv"),
                                                                      list.files(here::here("output", "sbe19plus_v0_align"),
                                                                                 full.names = TRUE, pattern = "upcast.cnv"))),
                                               optim_method = "SANN",
                                               min_pressure = 4,
                                               start_alpha = 0.04,
                                               start_tau = 8,
                                               obj_method = "area")

saveRDS(ctm_adjust_df, file = here::here("output", paste0(region, "_", year, "_", vessel, "_ctm_adjust_pars.rds")))

# Apply cell thermal mass correction
gapctd::run_method(vessel = vessel,
                   year = year,
                   region = region,
                   channel = channel,
                   processing_method = try_method,
                   storage_directory = here::here("output", paste0(try_method, "_ctm_adjust")),
                   ctd_dir = ctd_dir,
                   ctm_df = readRDS(file = here::here("output", paste0(region, "_", year, "_", vessel, "_ctm_adjust_pars.rds"))))

# Compare results
compare_df <- gapctd::compare_methods(prefix = "/binavg/align_ctd_method",
                                      method_labels = c("Estimated (Raw)", "Estimated (Aligned)", "Estimated (CTM-Area)", "Typical method"),
                                      processing_method = c("sbe19plus_v0", "sbe19plus_v0_align", "sbe19plus_v0_ctm_adjust", "sbe19plus_v2"),
                                      return_output = TRUE,
                                      pattern_downcast = "downcast_binavg.cnv",
                                      pattern_upcast = "upcast_binavg.cnv",
                                      scale_vars = FALSE,
                                      area_method = "ts")

##### MOVE FINAL FILES TO CNV DIR #####
gapctd::move_to_final_cnv(compare_df$best_df)

# Run density inversion check and correction
gapctd::correct_density_inversion(threshold = -1e-5, 
                                  threshold_method = "bv", 
                                  correct_inversion = TRUE, 
                                  cnv_dir = here::here("output", "sbe19plus_v0_ctm"), # Update to final_cnv
                                  pattern = "binavg")

# Manually review and flag bad data. Remove and interpolate bad data.
gapctd::manual_flag_interpolate()

# Review final data
gapctd::manual_review()

# Package files into a .zip
gapctd::make_ctd_zip(region = region, vessel = vessel, year = year)

# Package data product
### Separate code
```
